added pm2 configuration

diff --git a/.github/workflows/nuxt-to-aws.yml b/.github/workflows/nuxt-to-aws.yml
--- a/.github/workflows/nuxt-to-aws.yml
+++ b/.github/workflows/nuxt-to-aws.yml
@@ -32,19 +32,19 @@ jobs:
       - name: Check and Install PM2 if Not Installed
         uses: appleboy/ssh-action@master
         with:
-          key: ${{ secrets.AWS_EC2_DEPLOY_PEM_KEY }}
-          host: ${{ secrets.AWS_EC2_DEPLOY_IP_ADDRESS_HOST }}
-          username: ${{ secrets.AWS_EC2_DEPLOY_USER }}
-          port: ${{ secrets.AWS_EC2_DEPLOY_PORT }}
-          script: |
-            export PATH=$PATH:/home/ubuntu/.nvm/version/node/v22.8.0/bin
-            if ! command -v pm2 &> /dev/null
-            then
-              echo "PM2 not found. Installing PM2"
-              npm install -g pm2
-            else
-              echo "PM2 is already installed"
-            fi
+              key: ${{ secrets.AWS_EC2_DEPLOY_PEM_KEY }}
+              host: ${{ secrets.AWS_EC2_DEPLOY_IP_ADDRESS_HOST }}
+              username: ${{ secrets.AWS_EC2_DEPLOY_USER }}
+              port: ${{ secrets.AWS_EC2_DEPLOY_PORT }}
+              script: |
+                export PATH=$PATH:/home/ubuntu/.nvm/version/node/v22.8.0/bin
+                if ! command -v pm2 &> /dev/null
+                then
+                  echo "PM2 not found. Installing PM2"
+                  npm install -g pm2
+                else
+                  echo "PM2 is already installed"
+                fi
 
       - name: Restart PM2 process
         uses: appleboy/ssh-action@master
