Small fixes

diff --git a/.github/workflows/nuxt-to-aws.yml b/.github/workflows/nuxt-to-aws.yml
--- a/.github/workflows/nuxt-to-aws.yml
+++ b/.github/workflows/nuxt-to-aws.yml
@@ -29,31 +29,31 @@ jobs:
           SOURCE: ".output/"
           TARGET: "/home/ubuntu/nuxt-to-aws/.output"
 
-      - name: Check and Install PM2 if Not Installed
-        uses: appleboy/ssh-action@master
-        with:
-              key: ${{ secrets.AWS_EC2_DEPLOY_PEM_KEY }}
-              host: ${{ secrets.AWS_EC2_DEPLOY_IP_ADDRESS_HOST }}
-              username: ${{ secrets.AWS_EC2_DEPLOY_USER }}
-              port: ${{ secrets.AWS_EC2_DEPLOY_PORT }}
-              script: |
-                export PATH=$PATH:/home/ubuntu/.nvm/version/node/v22.8.0/bin
-                if ! command -v pm2 &> /dev/null
-                then
-                  echo "PM2 not found. Installing PM2"
-                  npm install -g pm2
-                else
-                  echo "PM2 is already installed"
-                fi
+      # - name: Check and Install PM2 if Not Installed
+      #   uses: appleboy/ssh-action@master
+      #   with:
+      #         key: ${{ secrets.AWS_EC2_DEPLOY_PEM_KEY }}
+      #         host: ${{ secrets.AWS_EC2_DEPLOY_IP_ADDRESS_HOST }}
+      #         username: ${{ secrets.AWS_EC2_DEPLOY_USER }}
+      #         port: ${{ secrets.AWS_EC2_DEPLOY_PORT }}
+      #         script: |
+      #           export PATH=$PATH:/home/ubuntu/.nvm/version/node/v22.8.0/bin
+      #           if ! command -v pm2 &> /dev/null
+      #           then
+      #             echo "PM2 not found. Installing PM2"
+      #             npm install -g pm2
+      #           else
+      #             echo "PM2 is already installed"
+      #           fi
 
-      - name: Restart PM2 process
-        uses: appleboy/ssh-action@master
-        with:
-          key: ${{ secrets.AWS_EC2_DEPLOY_PEM_KEY }}
-          host: ${{ secrets.AWS_EC2_DEPLOY_IP_ADDRESS_HOST }}
-          username: ${{ secrets.AWS_EC2_DEPLOY_USER }}
-          port: ${{ secrets.AWS_EC2_DEPLOY_PORT }}
-          script: |
-            export PATH=$PATH:/home/ubuntu/.nvm/version/node/v22.8.0/bin
-            cd /home/ubuntu/vanas-nuxt-aws-git-actions/.output
-            pm2 restart nux-app || pm2 start server/index.mjs --name "nuxt-app"
+      # - name: Restart PM2 process
+      #   uses: appleboy/ssh-action@master
+      #   with:
+      #     key: ${{ secrets.AWS_EC2_DEPLOY_PEM_KEY }}
+      #     host: ${{ secrets.AWS_EC2_DEPLOY_IP_ADDRESS_HOST }}
+      #     username: ${{ secrets.AWS_EC2_DEPLOY_USER }}
+      #     port: ${{ secrets.AWS_EC2_DEPLOY_PORT }}
+      #     script: |
+      #       export PATH=$PATH:/home/ubuntu/.nvm/version/node/v22.8.0/bin
+      #       cd /home/ubuntu/vanas-nuxt-aws-git-actions/.output
+      #       pm2 restart nux-app || pm2 start server/index.mjs --name "nuxt-app"
